spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      model: gpt-4o
      options:
        temperature: 0.3

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

security:
  access:
    permit-all:
      - /api/occupations/**
      - /css/**
      - /js/**
      - /img/**
      - /favicon.ico
      - /.well-known
      - /error/**
      - /auth/**
      - /
      - /main
      - /admin/login
      - /map_popup
      - /api/v1/auth/login
      - /api/v1/auth/refresh
      - /api/v1/attached/report-image-path/**
      - /api/v1/attached/summary-image-path/**
      - /search-page/**
      - /jobs/**
      - /community/**
      - /calendar
      - /job/**
      - /job/detail/**

      - /community/detail/**
      - /api/v1/chatbot/**
      - /api/calendar/**

      - /swagger-ui/**
      - /v3/api-docs
      - /v3/api-docs/**
      - /upload/**
      - /attached/company/**
    authenticated-paths:      #authenticated
      - /api/**
    member-paths:
      - /api/maps/**
      - /member/**
      - /community/write
      - /community/edit/**
      - /community/delete/**
      - /community/**
    company-paths:
      - /resumes/**
      - /company/**
      - /job/**
      - /api/occupations/**
    admin-paths:
      - /admin/**
    #      - /company/**
    #      - /job/**