server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${JDBC_DATABASE}
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    admin:
      enabled: false

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        highlight_sql: true

jwt:
  # issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

logging:
  level:
    # root: DEBUG
    org.hibernate.SQL: DEBUG

kakao:
  rest-api-key: "KakaoAK 95f4cb7367a36e2e71328edc2c4b9b07"
