jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

security:
  access:
    permit-all:
      - /css/**
      - /js/**
      - /favicon.ico
      - /.well-known
      - /error/**
      - /auth/**
      - /
      - /main
      - /admin/login
      - /map_popup
      - /api/v1/auth/login
      - /api/v1/auth/refresh
      - /search-page/**
      - /calendar

      - /search-page/**
      - /jobs/**
      - /community/**
    member-paths:
      - /api/maps/**
    company-paths:
      - /job/**
      - /company/**
    admin-paths:
      - /admin/**
    api-paths:
      - /api/**